[General]
ipv6 = false

[Proxy]
本机测试节点 = socks5,127.0.0.1,1080

[Proxy Group]
故障转移 = fallback,本机测试节点,url = https://cp.cloudflare.com/generate_204,interval = 300
金融服务 = select,故障转移,DIRECT

[Rule]
DOMAIN,api.example,金融服务
DOMAIN-SUFFIX,example.com,金融服务
DOMAIN-KEYWORD,market,金融服务
FINAL,故障转移
